export const CONTRACT_ABI = [
  "function owner() view returns (address)",
  "function ticketPrice() view returns (uint256)",
  "function duration() view returns (uint256)",
  "function lotteryEndTime() view returns (uint256)",
  "function lotteryState() view returns (uint8)",
  "function roundId() view returns (uint256)",
  "function lastCompletedRound() view returns (uint256)",
  "function totalTickets() view returns (uint256)",
  "function currentPot() view returns (uint256)",
  "function rolloverBalance() view returns (uint256)",
  "function recentWinner() view returns (address)",
  "function recentWinningTicket() view returns (uint256)",
  "function activeRequestId() view returns (uint256)",
  "function requestStartedAt() view returns (uint256)",
  "function vrfTimeout() view returns (uint256)",
  "function totalClaimable() view returns (uint256)",
  "function ticketsByRound(uint256,address) view returns (uint256)",
  "function claimableWinnings(address) view returns (uint256)",
  "function referrers(address) view returns (address)",
  "function getTicketOwner(uint256,uint256) view returns (address)",
  "function roundResults(uint256) view returns (address winner,uint256 winningTicket,uint256 randomWord,uint256 totalTickets,uint256 grossPot,uint256 prizeAmount,uint256 houseFee,address referrer,uint256 referrerReward,uint256 rolledOverAmount,uint256 completedAt,uint256 requestId)",
  "function buyTicket() payable",
  "function buyTicketWithReferrer(address) payable",
  "function buyTickets(uint256) payable",
  "function buyTicketsWithReferrer(uint256,address) payable",
  "function requestDraw() returns (uint256)",
  "function retryRandomness() returns (uint256)",
  "function withdrawWinnings(address payable)",
  "function checkUpkeep(bytes) view returns (bool,bytes)",
  "function performUpkeep(bytes)",
  "event TicketPurchased(uint256 indexed roundId,address indexed player,uint256 count,uint256 firstTicket,uint256 amount,address indexed referrer)",
  "event RandomnessRequested(uint256 indexed roundId,uint256 indexed requestId,bool retry)",
  "event WinnerPicked(uint256 indexed roundId,address indexed winner,uint256 winningTicket,uint256 randomWord,uint256 indexed requestId)",
  "event PayoutAllocated(uint256 indexed roundId,uint256 grossPot,uint256 prizeAmount,uint256 houseFee,address indexed referrer,uint256 referrerReward,uint256 rolledOverAmount)",
  "event WinningsWithdrawn(address indexed account,address indexed recipient,uint256 amount)",
] as const;
